theme: jekyll-theme-minimal
title: Daniel's Random Startup Ideas 
description: A semi-organised trash-heap of various ideas for startups that Daniel is too lazy to implement but wants somebody else to build